### ISSUE TITLE
Python2 issue with unicode

### ISSUE THREAD

**Issue by tjelvar-olsson** [jic-dtool/dtool-irods#9]
$ dtool copy ~/junk/test-unicode-ds irods:/jic_archive
Copying dataset  [------------------------------------]    0%
Traceback (most recent call last):
  File "/Users/olssont/envs/dtool/bin/dtool", line 11, in <module>
    sys.exit(dtool())
  File "/Users/olssont/envs/dtool/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/olssont/envs/dtool/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/olssont/envs/dtool/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/olssont/envs/dtool/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/olssont/envs/dtool/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/olssont/envs/dtool/lib/python2.7/site-packages/dtool_create/dataset.py", line 468, in copy
    progressbar=progressbar
  File "/Users/olssont/envs/dtool/lib/python2.7/site-packages/dtoolcore/__init__.py", line 190, in copy
    _copy_content(dataset, proto_dataset, progressbar)
  File "/Users/olssont/envs/dtool/lib/python2.7/site-packages/dtoolcore/__init__.py", line 167, in _copy_content
    dest_proto_dataset.put_readme(src_dataset.get_readme_content())
  File "/Users/olssont/envs/dtool/lib/python2.7/site-packages/dtoolcore/__init__.py", line 452, in put_readme
    self._storage_broker.put_readme(content)
  File "/Users/olssont/envs/dtool/lib/python2.7/site-packages/dtoolcore/storagebroker.py", line 248, in put_readme
    self.put_text(key, content)
  File "/Users/olssont/envs/dtool/lib/python2.7/site-packages/dtool_irods/storagebroker.py", line 381, in put_text
    _put_text(key, text)
  File "/Users/olssont/envs/dtool/lib/python2.7/site-packages/dtool_irods/storagebroker.py", line 89, in _put_text
    fh.write(text.encode())
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 14: ordinal not in range(128)

**Comment by tjelvar-olsson** [comment]
Fixed in e16e9dd
